export const HttpStatus = {
    OK: 200,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    INVALID_USERNAME_OR_PASSWORD: 402,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    UNSUPPORTED_MEDIA_TYPE: 415,
    UNPROCESSABLE_ENTITY: 422,
    ITEM_NOT_FOUND: 444,
    ITEM_ALREADY_EXIST: 445,
    ITEM_IS_USING: 446,
    INTERNAL_SERVER_ERROR: 500,
    OVER_LIMIT: 447,
    ITEM_IS_INVALID: 448,
};

export const MIN_PASSWORD_CHARACTER = 6;